pipeline {
   agent any


   stages {


       stage('Build') {
           steps {
                
                echo "Branch: ${env.BRANCH_NAME}"

                echo 'Building the application'
           }
       }


       stage('Test') {
           when {
               expression { env.BRANCH_NAME == 'dev' }
           }
           steps {
               echo 'Testing the application on ${env.BRANCH_NAME}'
           } 
       }


       stage('Deploy') {
           steps {
               echo 'Deploying the application'
           }
       }


   }


   post {
       always {
           echo 'This always runs'
       }


       success {
           echo 'Pipeline succeeded'
       }


       failure {
           echo 'Pipeline failed'
       }
   }
}
